##  Snowflake Data Setup

The transaction dataset was loaded into Snowflake for data preparation, validation, and SQL-based analysis.

### Database Structure

BANK ANALYTICS
└── RAW DATA
    └── TRANSACTIONS

CREATE DATABASE BANK_ANALYTICS;
CREATE SCHEMA RAW_DATA;
USE DATABASE BANK_ANALYTICS;
USE SCHEMA BANK_ANALYTICS.RAW_DATA;


-- =====================================================
-- 01. DATA QUALITY CHECKS
-- =====================================================


#1) DATA QUALITY CHECKS

#Total number of records

SELECT COUNT(*) AS total_rows
FROM TRANSACTIONS;

#Checking Nulls

SELECT
COUNT_IF(CARD_ID IS NULL) AS card_id_nulls,
COUNT_IF(TRANSACTION_ID IS NULL) AS transaction_id_nulls,
COUNT_IF(AMOUNT IS NULL) AS transaction_amount_nulls,
COUNT_IF(MERCHANT_ID IS NULL) AS merchant_id_nulls,
COUNT_IF(MERCHANT_CITY IS NULL) AS city_nulls,
COUNT_IF(MERCHANT_STATE IS NULL) AS state_nulls
FROM TRANSACTIONS;

#Duplicate Transaction IDs

SELECT 
COUNT(*) AS total_rows,
COUNT(DISTINCT TRANSACTION_ID) AS unique_transaction_ids
FROM transactions;

# Duplicate transaction records

SELECT
COUNT(*) AS TOTAL_ROWS,
COUNT(DISTINCT
        TRANSACTION_ID,
        CARD_ID,
        AMOUNT,
        DATE,
        MERCHANT_ID
    ) AS UNIQUE_RECORDS,
    COUNT(*) - COUNT(DISTINCT
        TRANSACTION_ID,
        CARD_ID,
        AMOUNT,
        DATE,
        MERCHANT_ID
    ) AS DUPLICATE_RECORDS
FROM TRANSACTIONS;

#TRANSACTION amounts

SELECT
MIN(AMOUNT) AS MIN_AMOUNT,
MAX(AMOUNT) AS MAX_AMOUNT,
COUNT_IF(AMOUNT <= 0) AS NON_POSITIVE_AMOUNT
FROM TRANSACTIONS;

#Age values

SELECT 
MIN(CURRENT_AGE) AS min_age,
MAX(CURRENT_AGE) AS max_age,
COUNT_IF(CURRENT_AGE < 18 OR CURRENT_AGE > 100) AS INVALID_AGES
FROM transactions;

# Birth year check

SELECT 
MIN(BIRTH_YEAR) AS min_birth_year,
MAX(BIRTH_YEAR) AS max_birth_year,
COUNT_IF(BIRTH_YEAR < 1900 OR BIRTH_YEAR > YEAR(CURRENT_DATE())) AS INVALID_BIRTH_YEARS
FROM transactions

#Age vs Birth Year consistency

SELECT
COUNT(*) AS INVALID_AGE_BIRTH_YEAR
FROM TRANSACTIONS
WHERE YEAR(CURRENT_DATE()) - BIRTH_YEAR <> AGE;

#Check transaction dates

SELECT
MIN(DATE) AS EARLIEST_TRANSACTION,
MAX(DATE) AS LATEST_TRANSACTION,
COUNT(DISTINCT DATE) AS UNIQUE_TRANSACTION_DATES
FROM TRANSACTIONS;

#Future transaction dates

SELECT
COUNT_IF(DATE > CURRENT_DATE()) AS FUTURE_DATES
FROM TRANSACTIONS;


-- =====================================================
-- B) BUSINESS ANALYSIS
-- =====================================================


-- =====================================================
--  1) CARD ANALYSIS
-- =====================================================


-- 1. Most Valuable Cards

SELECT
    CARD_ID,
    COUNT(*) AS TRANSACTION_COUNT,
    ROUND(SUM(AMOUNT), 2) AS TOTAL_SPENDING,
    ROUND(AVG(AMOUNT), 2) AS AVG_TRANSACTION_VALUE
FROM TRANSACTIONS
GROUP BY CARD_ID
ORDER BY TOTAL_SPENDING DESC
LIMIT 10;


-- 2. Card Usage Frequency

WITH Cte1 AS (
    SELECT
        CARD_ID,
        COUNT(*) AS TRANSACTION_COUNT
    FROM TRANSACTIONS
    GROUP BY CARD_ID
)
SELECT
    CASE
        WHEN TRANSACTION_COUNT BETWEEN 1 AND 2
            THEN 'Low Frequency'
        WHEN TRANSACTION_COUNT BETWEEN 3 AND 4
            THEN 'Medium Frequency'
        ELSE 'High Frequency'
    END AS USAGE_GROUP,
    COUNT(*) AS CARD_COUNT
FROM Cte1
GROUP BY USAGE_GROUP
ORDER BY CARD_COUNT DESC;


-- 3. Card Usage vs Spending

WITH Cte1 AS (
    SELECT
    CARD_ID,
    COUNT(*) AS TRANSACTION_COUNT,
    SUM(AMOUNT) AS TOTAL_SPENDING,
    AVG(AMOUNT) AS AVG_TRANSACTION_VALUE
    FROM TRANSACTIONS
    GROUP BY CARD_ID
)
SELECT
CASE
WHEN TRANSACTION_COUNT BETWEEN 1 AND 2
THEN 'Low Frequency'
WHEN TRANSACTION_COUNT BETWEEN 3 AND 4
THEN 'Medium Frequency'
ELSE 'High Frequency'
END AS USAGE_GROUP,
COUNT(*) AS CARD_COUNT,
SUM(TRANSACTION_COUNT) AS TOTAL_TRANSACTIONS,
ROUND(SUM(TOTAL_SPENDING), 2) AS TOTAL_SPENDING,
ROUND(AVG(AVG_TRANSACTION_VALUE), 2) AS AVG_TRANSACTION_VALUE
FROM CTE1
GROUP BY USAGE_GROUP
ORDER BY TOTAL_SPENDING DESC;

-- =====================================================
-- 02. MERCHANT ANALYSIS
-- =====================================================


-- 1. Merchant Performance by Transaction Volume

SELECT
MERCHANT_ID,
COUNT(*) AS TRNX_COUNT
FROM TRANSACTIONS
GROUP BY MERCHANT_ID
ORDER BY TRNX_COUNT DESC
LIMIT 10;


-- 2. Top 10 Merchant Spending Concentration

WITH cte1 AS (
    SELECT
        MERCHANT_ID,
        SUM(AMOUNT) AS TOTAL_SPENDING
    FROM TRANSACTIONS
    GROUP BY MERCHANT_ID
    ORDER BY TOTAL_SPENDING DESC
    LIMIT 10
)
SELECT
    ROUND(SUM(TOTAL_SPENDING), 2) AS TOP_10_SPENDING,
    ROUND((SELECT SUM(AMOUNT) FROM TRANSACTIONS), 2)
        AS OVERALL_SPENDING,
    ROUND(
        SUM(TOTAL_SPENDING)
        / (SELECT SUM(AMOUNT) FROM TRANSACTIONS) * 100,
        2
    ) AS PERCENTAGE
FROM cte1;


-- 3. Merchant Location Analysis

SELECT
MERCHANT_CITY,
MERCHANT_STATE,
COUNT(*) AS TRANSACTION_COUNT,
ROUND(SUM(AMOUNT), 2) AS TOTAL_SPENDING,
ROUND(AVG(AMOUNT), 2) AS AVG_TRANSACTION_VALUE
FROM TRANSACTIONS
GROUP BY MERCHANT_CITY, MERCHANT_STATE
ORDER BY TOTAL_SPENDING DESC;

-- =====================================================
-- 03. GEOGRAPHIC ANALYSIS
-- =====================================================


-- 1. State Performance

SELECT
    MERCHANT_STATE,
    COUNT(*) AS TRANSACTION_COUNT,
    ROUND(SUM(AMOUNT), 2) AS TOTAL_SPENDING,
    ROUND(AVG(AMOUNT), 2) AS AVG_TRANSACTION_VALUE
FROM TRANSACTIONS
GROUP BY MERCHANT_STATE
ORDER BY TOTAL_SPENDING DESC;


-- 2. City Performance

SELECT
    MERCHANT_CITY,
    COUNT(*) AS TRANSACTION_COUNT,
    ROUND(SUM(AMOUNT), 2) AS TOTAL_SPENDING,
    ROUND(AVG(AMOUNT), 2) AS AVG_TRANSACTION_VALUE
FROM TRANSACTIONS
GROUP BY MERCHANT_CITY
ORDER BY TOTAL_SPENDING DESC
LIMIT 10;

-- =====================================================
-- 04. SPENDING ANALYSIS
-- =====================================================


-- 1. Transaction Size Analysis

SELECT
CASE
WHEN AMOUNT <= 1000 THEN '0-1000'
WHEN AMOUNT <= 5000 THEN '1001-5000'
WHEN AMOUNT <= 10000 THEN '5001-10000'
WHEN AMOUNT <= 15000 THEN '10001-15000'
ELSE 'Above 15000'
END AS SPENDING_RANGE,
COUNT(*) AS TRANSACTION_COUNT,
ROUND(SUM(AMOUNT), 2) AS TOTAL_SPENDING,
ROUND(
        COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(),
        2
    ) AS TRANSACTION_PERCENTAGE

FROM TRANSACTIONS
GROUP BY 1
ORDER BY MIN(AMOUNT);


-- 2. Monthly Spending Trends

SELECT
    DATE_TRUNC('MONTH', DATE) AS MONTH,
    COUNT(*) AS TRANSACTION_COUNT,
    ROUND(SUM(AMOUNT), 2) AS TOTAL_SPENDING
FROM TRANSACTIONS
GROUP BY DATE_TRUNC('MONTH', DATE)
ORDER BY MONTH;


-- 3. Month-over-Month Spending Growth

WITH CTE1 AS (
    SELECT
        DATE_TRUNC('MONTH', DATE) AS MONTH,
        SUM(AMOUNT) AS TOTAL_SPENDING
    FROM TRANSACTIONS
    GROUP BY DATE_TRUNC('MONTH', DATE)
)
SELECT
    MONTH,
    ROUND(TOTAL_SPENDING, 2) AS TOTAL_SPENDING,
    ROUND(
        (
            TOTAL_SPENDING
            - LAG(TOTAL_SPENDING) OVER (ORDER BY MONTH)
        )
        / LAG(TOTAL_SPENDING) OVER (ORDER BY MONTH) * 100,
        2
    ) AS MOM_PERCENT_CHANGE
FROM CTE1
ORDER BY MONTH;

-- =====================================================
-- 06. TIME-BASED ANALYSIS
-- =====================================================


-- 1. Weekend vs Weekday Spending

SELECT
    CASE
        WHEN DAYOFWEEK(DATE) IN (1, 7)
            THEN 'Weekend'
        ELSE 'Weekday'
    END AS DAY_TYPE,

    COUNT(*) AS TRANSACTION_COUNT,

    ROUND(SUM(AMOUNT), 2) AS TOTAL_SPENDING,

    ROUND(AVG(AMOUNT), 2) AS AVG_TRANSACTION_VALUE

FROM TRANSACTIONS
GROUP BY DAY_TYPE
ORDER BY TOTAL_SPENDING DESC;

-- 2. Day-of-Week Analysis

SELECT
DAYNAME(DATE) AS DAY_NAME,
COUNT(*) AS TRANSACTION_COUNT,
ROUND(SUM(AMOUNT), 2) AS TOTAL_SPENDING,
ROUND(AVG(AMOUNT), 2) AS AVG_TRANSACTION_VALUE
FROM TRANSACTIONS
GROUP BY DAY_NAME
ORDER BY TOTAL_SPENDING DESC;

-- =====================================================
-- 07. HIGH-VALUE TRANSACTION ANALYSIS
-- =====================================================


-- 1. Top 10 Highest-Value Transactions

SELECT
CARD_ID,
AMOUNT,
MERCHANT_ID,
MERCHANT_CITY,
MERCHANT_STATE
FROM TRANSACTIONS
ORDER BY AMOUNT DESC
LIMIT 10;


-- 2. Highest-Value Transactions by State

SELECT
MERCHANT_STATE,
COUNT(*) AS HIGH_VALUE_TRANSACTIONS,
ROUND(MAX(AMOUNT), 2) AS HIGHEST_TRANSACTION,
ROUND(AVG(AMOUNT), 2) AS AVG_TRANSACTION_VALUE
FROM TRANSACTIONS
WHERE AMOUNT >= 10000
GROUP BY MERCHANT_STATE
ORDER BY HIGHEST_TRANSACTION DESC;

-- =====================================================
-- 08. OVERALL KPIs
-- =====================================================

SELECT
COUNT(*) AS TOTAL_TRANSACTIONS,
COUNT(DISTINCT CARD_ID) AS UNIQUE_CARDS,
COUNT(DISTINCT MERCHANT_ID) AS UNIQUE_MERCHANTS,
ROUND(SUM(AMOUNT), 2) AS TOTAL_SPENDING,
ROUND(AVG(AMOUNT), 2) AS AVG_TRANSACTION_VALUE,
ROUND(MAX(AMOUNT), 2) AS HIGHEST_TRANSACTION,
MIN(DATE) AS FIRST_TRANSACTION_DATE,
MAX(DATE) AS LAST_TRANSACTION_DATE
FROM TRANSACTIONS;

    
